version: '3.9'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - database_hostname=db
      - database_port=5432
      - database_username=postgres
      - database_password=MyStrongPass2025!@#
      - database_name=store_db
      - secret_key=0c9fb45278f32db29e55e18d138d02230f57d9b668251cc3
      - algorithm=HS256
      - access_token_expire_minutes=60
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: store_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MyStrongPass2025!@#
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  postgres_data: